import Head from "next/head";
import Image from "next/image";
import Card from "../components/card";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-100">
      <Head>
        <title>Nooc&apos;s World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <div className="w-full px-4 py-16 sm:px-6 lg:px-8">
            <div className="mx-auto grid max-w-screen-lg grid-cols-1 gap-4 sm:grid-cols-2">
              <Card className="row-span-2">Nooc</Card>
              <Card>Hello</Card>
              <Card>World</Card>
            </div>
          </div>
        </section>
      </main>

      <footer className="text-md text-center text-gray-400">© 2022 Nooc</footer>
    </div>
  );
}
