name: Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: | 
          npm install
          npm build

      - name: deploy
        env: 
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npm run deploy
